base_url = "https://nilsso.github.io"
title = "nilsso"
description = "Personal site"
default_language = "en"
highlight_code = true
highlight_theme = "nord"
taxonomies = [
    { name = "tags" }
]
compile_sass = true
extra_syntaxes = ["syntaxes"]

[extra]
user = "nilsso"
github = "https://github.com/nilsso"
#home_links = ["pages/programming", "pages/math", "pages/music", "pages/games"]
home_links = ["pages", "projects"]
