on: push
name: Build and deploy on push
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: code
    - uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: master
        TOKEN: ${{ secrets.TOKEN }}
